#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Mar 08, 2015 02:35:34 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import parking40_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    root.title('Parking_4.0')
    geom = "600x390+100+179"
    root.geometry(geom)
    w = Parking_4.0 (root)
    parking40_support.init(root, w)
    root.mainloop()

w = None
def create_Parking_4.0(root, param=None):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    w.title('Parking_4.0')
    geom = "600x390+100+179"
    w.geometry(geom)
    w_win = Parking_4.0 (w)
    parking40_support.init(w, w_win, param)
    return w_win

def destroy_Parking_4.0():
    global w
    w.destroy()
    w = None


class Parking_4.0:
    def __init__(self, master=None):
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        master.configure(background="#d9d9d9")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")


        self.menubar = Menu(master,bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

        self.user = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.user,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="User")
        self.user.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="Login")
        self.user.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="Exit")
        self.car_operation = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.car_operation,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="Car Operation")
        self.car_operation.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="I want to park the car")
        self.car_operation.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="I want to select a parking place")
        self.car_operation.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="I park the car")
        self.car_operation.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="I start the car")
        self.community = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.community,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="Community")
        self.community.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="I want to tell a parking place")
        self.community.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="I want to tell about a parkiing restriction")
        self.community.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="I am an Authority and want to schedule parking conditions")
        self.community.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="I claim an urgent removal of a car")
        self.help = Menu(master,tearoff=0)
        self.menubar.add_cascade(menu=self.help,
                activebackground="#d9d9d9",
                activeforeground="#111111",
                background="#d9d9d9",
                foreground="#000000",
                label="Help")
        self.help.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="About Parking 4.0")
        self.help.add_command(
                activebackground="#d9d9d9",
                activeforeground="#000000",
                background="#d9d9d9",
                command=parking40_support.TODO,
                foreground="#000000",
                label="Open Help")







if __name__ == '__main__':
    vp_start_gui()



