#############################################################################
# Generated by PAGE version 4.5
# in conjunction with Tcl version 8.6
#    Mar 08, 2015 02:35:28 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top37
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    set site_3_0 $base.m38
    set site_3_0 $base.m38
    set site_3_0 $base.m38
    set site_3_0 $base.m38
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top37 {base} {
    if {$base == ""} {
        set base .top37
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m38" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 600x390+100+179
    update
    # set in toplevel.wgt.
    global vTcl
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1020 721
    wm minsize $top 124 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Parking 4.0"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    ttk::style configure Menu -background #d9d9d9
    ttk::style configure Menu -foreground #000000
    ttk::style configure Menu -font TkDefaultFont
    menu $top.m38 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $top.m38 add cascade \
        -menu "$top.m38.men39" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label User 
    set site_3_0 $top.m38
    menu $site_3_0.men39 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men39 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label Login 
    $site_3_0.men39 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label Exit 
    $top.m38 add cascade \
        -menu "$top.m38.men41" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label {Car Operation} 
    set site_3_0 $top.m38
    menu $site_3_0.men41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men41 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label {I want to park the car} 
    $site_3_0.men41 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label {I want to select a parking place} 
    $site_3_0.men41 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label {I park the car} 
    $site_3_0.men41 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label {I start the car} 
    $top.m38 add cascade \
        -menu "$top.m38.men42" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Community 
    set site_3_0 $top.m38
    menu $site_3_0.men42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men42 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label {I want to tell a parking place} 
    $site_3_0.men42 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} \
        -label {I want to tell about a parkiing restriction} 
    $site_3_0.men42 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} \
        -label {I am an Authority and want to schedule parking conditions} 
    $site_3_0.men42 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label {I claim an urgent removal of a car} 
    $top.m38 add cascade \
        -menu "$top.m38.men44" -activebackground {#d9d9d9} \
        -activeforeground {#111111} -background {#d9d9d9} -font TkMenuFont \
        -foreground {#000000} -label Help 
    set site_3_0 $top.m38
    menu $site_3_0.men44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font {{Segoe UI} 9} -foreground black \
        -tearoff 0 
    $site_3_0.men44 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label {About Parking 4.0} 
    $site_3_0.men44 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -command TODO -font TkMenuFont \
        -foreground {#000000} -label {Open Help} 
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top37

